/*
 * This file is generated by jOOQ.
 */
package com.github.propan.teabuddy.repository.jooq;


import com.github.propan.teabuddy.repository.jooq.tables.Crawlers;
import com.github.propan.teabuddy.repository.jooq.tables.Items;
import com.github.propan.teabuddy.repository.jooq.tables.records.CrawlersRecord;
import com.github.propan.teabuddy.repository.jooq.tables.records.ItemsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CrawlersRecord> CONSTRAINT_9 = Internal.createUniqueKey(Crawlers.CRAWLERS, DSL.name("CONSTRAINT_9"), new TableField[] { Crawlers.CRAWLERS.ID }, true);
    public static final UniqueKey<ItemsRecord> CONSTRAINT_4 = Internal.createUniqueKey(Items.ITEMS, DSL.name("CONSTRAINT_4"), new TableField[] { Items.ITEMS.ID }, true);
}
