/*
 * This file is generated by jOOQ.
 */
package com.github.propan.teabuddy.repository.jooq;


import com.github.propan.teabuddy.repository.jooq.tables.Crawlers;
import com.github.propan.teabuddy.repository.jooq.tables.Items;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CRAWLERS</code>.
     */
    public final Crawlers CRAWLERS = Crawlers.CRAWLERS;

    /**
     * The table <code>PUBLIC.ITEMS</code>.
     */
    public final Items ITEMS = Items.ITEMS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Crawlers.CRAWLERS,
            Items.ITEMS
        );
    }
}
