/*
 * This file is generated by jOOQ.
 */
package com.github.propan.teabuddy.repository.jooq;


import com.github.propan.teabuddy.repository.jooq.tables.Crawlers;
import com.github.propan.teabuddy.repository.jooq.tables.Items;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.CRAWLERS</code>.
     */
    public static final Crawlers CRAWLERS = Crawlers.CRAWLERS;

    /**
     * The table <code>PUBLIC.ITEMS</code>.
     */
    public static final Items ITEMS = Items.ITEMS;
}
